Repository infinitered/ignite, pull requests merged in 2022-08, with the labels that each got.

#1965 Default Splash Screen Implementation; Splash Screen Generator
  boilerplate/android/app/build.gradle
  boilerplate/android/app/src/main/AndroidManifest.xml
  boilerplate/android/app/src/main/java/com/helloworld/MainActivity.java
  boilerplate/android/app/src/main/res/mipmap-hdpi/bootsplash_logo.png
  boilerplate/android/app/src/main/res/mipmap-mdpi/bootsplash_logo.png
  boilerplate/android/app/src/main/res/mipmap-xhdpi/bootsplash_logo.png
  boilerplate/android/app/src/main/res/mipmap-xxhdpi/bootsplash_logo.png
  boilerplate/android/app/src/main/res/mipmap-xxxhdpi/bootsplash_logo.png
  boilerplate/android/app/src/main/res/values/colors.xml
  boilerplate/android/app/src/main/res/values/styles.xml
  boilerplate/android/build.gradle
  boilerplate/app.json
  boilerplate/app/app.tsx
  boilerplate/assets/images/splash-logo-all.png
  boilerplate/assets/images/splash-logo-android-universal.png
  boilerplate/assets/images/splash-logo-ios-mobile.png
  boilerplate/assets/images/splash-logo-ios-tablet.png
  boilerplate/assets/images/splash-logo-web.png
  boilerplate/ignite/templates/splash-screen/logo.png
  boilerplate/index.expo.js
  boilerplate/index.js
  boilerplate/ios/HelloWorld.xcodeproj/project.pbxproj
  boilerplate/ios/HelloWorld/AppDelegate.mm
  boilerplate/ios/HelloWorld/BootSplash.storyboard
  boilerplate/ios/HelloWorld/Images.xcassets/BootSplashLogo.imageset/Contents.json
  boilerplate/ios/HelloWorld/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo.png
  boilerplate/ios/HelloWorld/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@2x.png
  boilerplate/ios/HelloWorld/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@3x.png
  boilerplate/ios/HelloWorld/Info.plist
  boilerplate/ios/HelloWorld/LaunchScreen.storyboard
  boilerplate/ios/Podfile.lock
  boilerplate/package.expo.json
  boilerplate/package.json
  boilerplate/yarn.lock
  docs/Generators.md
  src/commands/generate/splash-screen.ts
  src/commands/new.ts
  src/tools/generators.ts
  test/_test-helpers.ts
Labels: maverick

#1630 Add front matter support to templates
  boilerplate/ignite/templates/component/NAME.tsx.ejs
  boilerplate/ignite/templates/model/NAME.ts.ejs
  boilerplate/ignite/templates/navigator/NAME-navigator.tsx.ejs
  boilerplate/ignite/templates/screen/NAME-screen.tsx.ejs
  docs/Generators.md
  package.json
  src/commands/generate.ts
  src/tools/generators.ts
Labels: maverick

#1980 Docs/navigation styling
  boilerplate/app/navigators/app-navigator.tsx
  boilerplate/app/navigators/navigation-utilities.tsx
  docs/Generators.md
  docs/Navigation.md
  docs/README.md
  docs/Styling.md
  docs/Testing.md
  docs/Upgrades.md
Labels: maverick

#2009 Fix screen and component generator output in `ignite new` test case
  boilerplate/ignite/templates/component/NAME.tsx.ejs
  boilerplate/ignite/templates/screen/NAME-screen.tsx.ejs
  boilerplate/package.json
  test/_test-helpers.ts
  test/vanilla/ignite-new.test.ts
Labels: bug, maverick

#2010 Internationalization Updates
  boilerplate/app/components/Header.tsx
  boilerplate/app/components/Text.tsx
  boilerplate/app/components/TextField.tsx
  boilerplate/app/i18n/ar.json
  boilerplate/app/i18n/en.json
  boilerplate/app/i18n/i18n.ts
  boilerplate/app/i18n/ja.json
  boilerplate/app/i18n/ko.json
  boilerplate/app/screens/DemoComponentsScreen/DemoComponentsScreen.tsx
  boilerplate/app/screens/DemoComponentsScreen/DrawerIconButton.tsx
  boilerplate/app/screens/DemoDebugScreen.tsx
  boilerplate/app/screens/WelcomeScreen.tsx
  boilerplate/ios/Podfile.lock
  boilerplate/tsconfig.json
  docs/Internationalization.md
  docs/README.md
Labels: maverick

#2015 Theming initial documentation
  boilerplate/app/theme/colors.ts
  boilerplate/app/theme/typography.ts
  docs/README.md
  docs/Styling.md
  docs/Theming-Colors-And-Palettes.md
  docs/Theming-Fonts-And-Typography.md
  docs/Theming.md
Labels: in progress, maverick

#2033 Enhancement: Enable Hermes engine by default
  README.md
  boilerplate/android/app/build.gradle
  boilerplate/app.json
  boilerplate/ios/Podfile
  boilerplate/ios/Podfile.lock
Labels: maverick

#2027 Adds DemoCommunityScreen. Adds ListItem component.
  boilerplate/app/components/Header.tsx
  boilerplate/app/components/Icon.tsx
  boilerplate/app/components/ListItem.tsx
  boilerplate/app/components/form-row/form-row.presets.ts
  boilerplate/app/components/form-row/form-row.props.tsx
  boilerplate/app/components/form-row/form-row.tsx
  boilerplate/app/components/index.ts
  boilerplate/app/i18n/ar.json
  boilerplate/app/i18n/ar.ts
  boilerplate/app/i18n/en.json
  boilerplate/app/i18n/en.ts
  boilerplate/app/i18n/i18n.ts
  boilerplate/app/i18n/ko.json
  boilerplate/app/i18n/ko.ts
  boilerplate/app/navigators/DemoNavigator.tsx
  boilerplate/app/screens/DemoCommunityScreen.tsx
  boilerplate/app/screens/DemoComponentsScreen/DemoComponentsScreen.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/DemoButton.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/DemoListItem.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/index.ts
  boilerplate/app/screens/index.ts
  boilerplate/assets/icons/clap.png
  boilerplate/assets/icons/clap@2x.png
  boilerplate/assets/icons/clap@3x.png
  boilerplate/assets/icons/github.png
  boilerplate/assets/icons/github@2x.png
  boilerplate/assets/icons/github@3x.png
  boilerplate/assets/icons/slack.png
  boilerplate/assets/icons/slack@2x.png
  boilerplate/assets/icons/slack@3x.png
  boilerplate/assets/images/cr-logo.png
  boilerplate/assets/images/cr-logo@2x.png
  boilerplate/assets/images/cr-logo@3x.png
  boilerplate/assets/images/rnl-logo.png
  boilerplate/assets/images/rnl-logo@2x.png
  boilerplate/assets/images/rnl-logo@3x.png
  boilerplate/assets/images/rnn-logo.png
  boilerplate/assets/images/rnn-logo@2x.png
  boilerplate/assets/images/rnn-logo@3x.png
  boilerplate/assets/images/rnr-logo.png
  boilerplate/assets/images/rnr-logo@2x.png
  boilerplate/assets/images/rnr-logo@3x.png
  boilerplate/test/i18n.test.ts
  docs/Components-FormRow.md
  docs/Components-ListItem.md
  docs/Components.md
Labels: maverick

#1999 Add prompts and flags for `ignite new` command options
  README.md
  package.json
  src/commands/new.ts
  src/tools/packager.ts
  src/tools/react-native.ts
  src/tools/validations.ts
  test/_test-helpers.ts
  test/vanilla/ignite-new.test.ts
  yarn.lock
Labels: maverick

#2036 Fixes RNR screen initial load and first-run UX on login screen
  boilerplate/app/screens/DemoComponentsScreen/DemoComponentsScreen.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/DemoTextField.tsx
  boilerplate/app/screens/DemoPodcastListScreen.tsx
  boilerplate/app/screens/LoginScreen.tsx
  boilerplate/ios/Podfile.lock
  boilerplate/package.json
  boilerplate/test/mock-react-native-image.ts
  boilerplate/tsconfig.json
Labels: maverick

#2038 fix(screen): fixed StatusBar styling for Android
  boilerplate/app/components/Screen.tsx
Labels: maverick

#2042 Remove undefined flag values from `new` command output
  src/commands/new.ts
Labels: bug, maverick

#2041 Update Header component documentation to reflect maverick changes
  docs/Components-Header.md
Labels: maverick

#2040 Feat(maverick): add debug screen
  boilerplate/android/app/src/main/AndroidManifest.xml
  boilerplate/app/i18n/ar.ts
  boilerplate/app/i18n/en.ts
  boilerplate/app/i18n/ko.ts
  boilerplate/app/screens/DemoDebugScreen.tsx
  boilerplate/ios/HelloWorld.xcodeproj/project.pbxproj
  boilerplate/ios/Podfile.lock
Labels: in progress, maverick

#2053 Maverick rnr link
  boilerplate/app/i18n/ar.ts
  boilerplate/app/i18n/en.ts
  boilerplate/app/i18n/ko.ts
  boilerplate/app/models/EpisodeStore.ts
  boilerplate/app/navigators/DemoNavigator.tsx
  boilerplate/app/screens/DemoCommunityScreen.tsx
  boilerplate/app/screens/DemoPodcastListScreen.tsx
  boilerplate/app/utils/open-link-in-browser.ts
Labels: maverick

#2054 Update TextField component documentation to reflect maverick changes.
  docs/Components-TextField.md
Labels: maverick

#2046 Implemented useScrollToTop
  boilerplate/app/components/Screen.tsx
Labels: enhancement, maverick

#2039 Add `remove-demo` command
  docs/Remove-Demo-Code.md
  src/commands/remove-demo.ts
  src/tools/__snapshots__/demo.test.ts.snap
  src/tools/__snapshots__/path.test.ts.snap
  src/tools/demo.test.ts
  src/tools/demo.ts
  src/tools/path.test.ts
  src/tools/path.ts
  test/vanilla/__snapshots__/ignite-remove-demo.test.ts.snap
  test/vanilla/ignite-remove-demo.test.ts
Labels: enhancement, maverick

#2067 Maverick Styling and Date to account for i18n (and RTL)
  boilerplate/app/components/Button.tsx
  boilerplate/app/components/ListItem.tsx
  boilerplate/app/components/TextField.tsx
  boilerplate/app/components/bullet-item/bullet-item.tsx
  boilerplate/app/components/checkbox/checkbox.tsx
  boilerplate/app/models/Episode.test.ts
  boilerplate/app/models/Episode.ts
  boilerplate/app/screens/DemoCommunityScreen.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/DemoListItem.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/DemoTextField.tsx
  boilerplate/app/screens/DemoPodcastListScreen.tsx
  boilerplate/app/utils/format-date.ts
  docs/Components-Checkbox.md
  docs/Components.md
Labels: maverick

#2062 Fix `new` command target directory flag for non-default arguments
  src/commands/new.ts
  src/tools/flag.ts
  src/tools/react-native.ts
Labels: bug, maverick

#2065 miscellaneous Maverick tweaks
  boilerplate/app/components/Button.tsx
  boilerplate/app/components/Icon.tsx
  boilerplate/app/components/ListItem.tsx
  boilerplate/app/components/TextField.tsx
  boilerplate/app/components/bullet-item/bullet-item.tsx
  boilerplate/app/components/checkbox/checkbox.tsx
  boilerplate/app/models/Episode.test.ts
  boilerplate/app/models/Episode.ts
  boilerplate/app/navigators/DemoNavigator.tsx
  boilerplate/app/screens/DemoCommunityScreen.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/DemoListItem.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/DemoTextField.tsx
  boilerplate/app/screens/DemoPodcastListScreen.tsx
  boilerplate/app/utils/format-date.ts
  boilerplate/assets/icons/podcast.png
  boilerplate/assets/icons/podcast@2x.png
  boilerplate/assets/icons/podcast@3x.png
  boilerplate/ios/Podfile.lock
  docs/Components-Checkbox.md
  docs/Components.md
Labels: maverick

#2066 fix(component): Fix for scrollToIndex failed on Demo Screen
  boilerplate/app/screens/DemoComponentsScreen/DemoComponentsScreen.tsx
Labels: maverick

#2069 Convert all values to boolean in `new` command, shorten suggested command flags
  src/commands/new.ts
Labels: enhancement, maverick

#2078 Remove `}` from `false` flag suggestion after `new` command
  src/commands/new.ts
Labels: bug, maverick

#2072 add glob constraints to remove-demo command
  boilerplate/app/screens/DemoComponentsScreen/DemoComponentsScreen.tsx
  docs/Components-TextField.md
  src/commands/remove-demo.ts
  src/tools/__snapshots__/path.test.ts.snap
  src/tools/path.test.ts
  src/tools/path.ts
  test/vanilla/ignite-remove-demo.test.ts
Labels: maverick

#2081 Fix `remove-demo` command from removing the first line of every file with `@demo remove-next-line`
  src/tools/__snapshots__/demo.test.ts.snap
  src/tools/demo.test.ts
  src/tools/demo.ts
Labels: bug, maverick

#2083 fix(i18n): Fixes direction of caret on links for RTL
  boilerplate/app/screens/DemoCommunityScreen.tsx
  boilerplate/app/screens/DemoDebugScreen.tsx
Labels: maverick

#2073 chore(boilerplate): update to new spacing scale with named properties
  boilerplate/app/components/Button.tsx
  boilerplate/app/components/Header.tsx
  boilerplate/app/components/ListItem.tsx
  boilerplate/app/components/TextField.tsx
  boilerplate/app/components/bullet-item/bullet-item.tsx
  boilerplate/app/components/checkbox/checkbox.tsx
  boilerplate/app/components/switch/switch.tsx
  boilerplate/app/navigators/DemoNavigator.tsx
  boilerplate/app/screens/DemoCommunityScreen.tsx
  boilerplate/app/screens/DemoComponentsScreen/DemoComponentsScreen.tsx
  boilerplate/app/screens/DemoComponentsScreen/DemoUseCase.tsx
  boilerplate/app/screens/DemoComponentsScreen/DrawerIconButton.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/DemoIcon.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/DemoListItem.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/DemoTextField.tsx
  boilerplate/app/screens/DemoDebugScreen.tsx
  boilerplate/app/screens/ErrorScreen/ErrorDetails.tsx
  boilerplate/app/screens/LoginScreen.tsx
Labels: in progress, maverick

#2082 2055 accessibility
  boilerplate/app/components/Button.tsx
  boilerplate/app/components/Icon.tsx
  boilerplate/app/components/TextField.tsx
  boilerplate/app/components/switch/switch.props.ts
  boilerplate/app/components/switch/switch.tsx
  boilerplate/app/i18n/ar.ts
  boilerplate/app/i18n/en.ts
  boilerplate/app/i18n/ko.ts
  boilerplate/app/i18n/translate.ts
  boilerplate/app/models/Episode.test.ts
  boilerplate/app/models/Episode.ts
  boilerplate/app/screens/DemoPodcastListScreen.tsx
  boilerplate/test/mock-i18n.ts
Labels: maverick

#2076 Prevent `new` command error when installing deps
  src/commands/new.ts
Labels: maverick

#2089 Run all tests in CI
  .circleci/config.yml
  package.json
  tsconfig.json
Labels: maverick

#2085 Update ListItem component documentation
  docs/Components-ListItem.md
  docs/Components-TextField.md
Labels: maverick
