Repository infinitered/ignite, pull requests merged in 2022-09, with the labels that each got.

#2092 Explicitly call process.exit(0) at the end of the `new` command
  src/commands/new.ts
Labels: bug, maverick

#2107 Toggle Component
  boilerplate/app/components/TextField.tsx
  boilerplate/app/components/Toggle.tsx
  boilerplate/app/components/bullet-item/bullet-item.tsx
  boilerplate/app/components/checkbox/checkbox.props.ts
  boilerplate/app/components/checkbox/checkbox.tsx
  boilerplate/app/components/index.ts
  boilerplate/app/components/switch/switch.props.ts
  boilerplate/app/components/switch/switch.tsx
  boilerplate/app/i18n/ar.ts
  boilerplate/app/i18n/en.ts
  boilerplate/app/i18n/ko.ts
  boilerplate/app/screens/DemoComponentsScreen/demos/DemoToggle.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/index.ts
  boilerplate/app/screens/DemoPodcastListScreen.tsx
  boilerplate/app/theme/colors.ts
  docs/Components-BulletItem.md
  docs/Components-Checkbox.md
  docs/Components-ListItem.md
  docs/Components-Switch.md
  docs/Components-TextField.md
  docs/Components.md
Labels: maverick

#2116 Fix `--overwrite` in `new` command for not default target path
  src/commands/new.ts
Labels: bug, maverick

#2080 Speed up `new` command by caching dependencies locally
  .circleci/config.yml
  src/commands/cache.ts
  src/commands/new.ts
  src/tools/cache.ts
  src/tools/pretty.ts
Labels: enhancement, maverick

#2120 Card component; AutoImage enhancement; Podcast Screen updates.
  boilerplate/app/components/AutoImage.tsx
  boilerplate/app/components/Button.tsx
  boilerplate/app/components/Card.tsx
  boilerplate/app/components/Text.tsx
  boilerplate/app/components/index.ts
  boilerplate/app/i18n/ar.ts
  boilerplate/app/i18n/en.ts
  boilerplate/app/i18n/ko.ts
  boilerplate/app/models/Episode.ts
  boilerplate/app/screens/DemoComponentsScreen/demos/DemoAutoImage.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/DemoCard.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/DemoListItem.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/index.ts
  boilerplate/app/screens/DemoPodcastListScreen.tsx
Labels: maverick

#2123 Improve CI test job speed
  .circleci/config.yml
  .prettierignore
  package.json
  test/_test-helpers.ts
  test/vanilla/ignite-new.test.ts
  yarn.lock
Labels: bug, maverick

#2127 Improves generator update output
  src/tools/generators.ts
Labels: maverick

#2124 Adds Expo + Ignite docs
  docs/Expo-and-Ignite.md
Labels: maverick

#2108 feat(boilerplate): add empty state component to demoPodcastListScreen
  boilerplate/app/i18n/ar.ts
  boilerplate/app/i18n/en.ts
  boilerplate/app/i18n/ko.ts
  boilerplate/app/screens/DemoCommunityScreen.tsx
  boilerplate/app/screens/DemoDebugScreen.tsx
  boilerplate/app/screens/DemoPodcastListScreen.tsx
  boilerplate/assets/images/sad-face.png
  boilerplate/assets/images/sad-face@2x.png
  boilerplate/assets/images/sad-face@3x.png
Labels: maverick

#2129 Maverick fix set dev snack
  boilerplate/app/app.tsx
  boilerplate/app/utils/set-dev.js
  boilerplate/ios/Podfile.lock
Labels: maverick

#2131 Add ./android/app/src/main/assets folder
  boilerplate/android/app/src/main/assets/.gitkeep
Labels: maverick

#2119 Update `new`, `help`, output styles
  package.json
  src/assets/index.ts
  src/assets/logo-sm.ascii.txt
  src/assets/logo.ascii.txt
  src/commands/help.ts
  src/commands/new.ts
  src/tools/pretty.ts
  src/tools/pretty/index.ts
  src/tools/pretty/print.ts
  src/tools/pretty/prompt.ts
  src/tools/pretty/spinners.ts
  src/tools/pretty/theme.ts
  src/tools/validations.ts
  test/vanilla/ignite-new.test.ts
Labels: enhancement, design, maverick

#2058 Snackify maverick
  src/commands/snackify.ts
Labels: maverick

#2142 Switching to async for copy/remove
  package.json
  src/commands/cache.ts
  src/commands/new.ts
  src/tools/cache.ts
Labels: maverick

#2140 Add @demo remove-* comments to boilerplate
  boilerplate/app/i18n/ar.ts
  boilerplate/app/i18n/en.ts
  boilerplate/app/i18n/ko.ts
  boilerplate/app/models/AuthenticationStore.ts
  boilerplate/app/models/Episode.test.ts
  boilerplate/app/models/Episode.ts
  boilerplate/app/models/EpisodeStore.ts
  boilerplate/app/models/RootStore.ts
  boilerplate/app/navigators/AppNavigator.tsx
  boilerplate/app/navigators/DemoNavigator.tsx
  boilerplate/app/screens/DemoCommunityScreen.tsx
  boilerplate/app/screens/DemoComponentsScreen/DemoComponentsScreen.tsx
  boilerplate/app/screens/DemoComponentsScreen/DemoDivider.tsx
  boilerplate/app/screens/DemoComponentsScreen/DemoUseCase.tsx
  boilerplate/app/screens/DemoComponentsScreen/DrawerIconButton.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/DemoAutoImage.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/DemoButton.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/DemoCard.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/DemoHeader.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/DemoIcon.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/DemoListItem.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/DemoText.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/DemoTextField.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/DemoToggle.tsx
  boilerplate/app/screens/DemoComponentsScreen/demos/index.ts
  boilerplate/app/screens/DemoDebugScreen.tsx
  boilerplate/app/screens/DemoPodcastListScreen.tsx
  boilerplate/app/screens/LoginScreen.tsx
  boilerplate/app/screens/WelcomeScreen.tsx
  boilerplate/app/screens/index.ts
  boilerplate/app/services/api/api.ts
  src/commands/remove-demo.ts
  src/tools/__snapshots__/demo.test.ts.snap
  src/tools/demo.test.ts
  src/tools/demo.ts
  test/vanilla/__snapshots__/ignite-remove-demo.test.ts.snap
Labels: enhancement, maverick, cli

#2144 Add `--dry-run` to `remove-demo` command
  docs/Remove-Demo-Code.md
  src/commands/remove-demo.ts
Labels: maverick

#2155 Add `--use-cache` flag to `new` command test
  test/vanilla/ignite-new.test.ts
Labels: enhancement, maverick

#2156 Fix AppNavigator whitespace error, fix EpisodeCard rendering issue
  boilerplate/app/navigators/AppNavigator.tsx
  boilerplate/app/screens/DemoPodcastListScreen.tsx
Labels: bug, maverick

#2157 refactor(boilerplate): run `yarn format`
  boilerplate/app/i18n/ar.ts
  boilerplate/app/i18n/en.ts
  boilerplate/app/i18n/ko.ts
  boilerplate/app/navigators/AppNavigator.tsx
  boilerplate/app/screens/DemoComponentsScreen/DemoUseCase.tsx
  boilerplate/app/screens/DemoPodcastListScreen.tsx
  boilerplate/app/screens/WelcomeScreen.tsx
  boilerplate/app/services/api/api.ts
Labels: maverick

#2158 Move `// @demo remove-block-start` in AppNavigator
  boilerplate/app/navigators/AppNavigator.tsx
Labels: bug, maverick, cli

#2154 Handle relative paths and `~` character in `--target-path` of `new` command
  src/commands/new.ts
Labels: bug, maverick, cli

#2159 Add test for `ignite generate model` and update Generator Template docs
  docs/Generator-Templates.md
  test/vanilla/ignite-generate.test.ts
Labels: docs, maverick

#2160 docs(component): Create documentation for the new maverick Card component
  boilerplate/app/components/Card.tsx
  docs/Components-Card.md
  docs/Components.md
Labels: maverick

#2153 fix(docs): update docs for icon generator
  docs/Generators.md
Labels: maverick

#2149 Simplify highlights in `new` command
  src/commands/new.ts
  src/tools/pretty.ts
Labels: maverick, cli

#2139 feat(generator): custom file names
  boilerplate/ignite/templates/navigator/NAMENavigator.tsx.ejs
  boilerplate/ignite/templates/screen/NAMEScreen.tsx.ejs
  docs/Generator-Templates.md
  src/tools/generators.ts
Labels: on hold, maverick

#2161 Add `validateProjectName` guards to prompt
  src/tools/validations.ts
Labels: enhancement, maverick

#2162 Maverick readme
  README.md
  docs/Guide.md
Labels: docs, maverick

#2164 Maverick troubleshooting setup
  docs/Guide.md
  docs/README.md
  docs/Upgrading-Ignite.md
Labels: docs, maverick

#2165 fix(new): add optional chain to 'startsWith' in parsePath
  src/commands/new.ts
Labels: bug, maverick, cli

#2167 fix(DrawerIconButton): animate pressible instead of view
  boilerplate/app/screens/DemoComponentsScreen/DrawerIconButton.tsx
Labels: bug, maverick

#2171 fix(cache): copy .xcode.env.local
  src/tools/cache.ts
Labels: bug, maverick, cli

#2138 Community, podcast, and debug screen design updates
  boilerplate/app/components/Toggle.tsx
  boilerplate/app/i18n/ar.ts
  boilerplate/app/i18n/en.ts
  boilerplate/app/i18n/ko.ts
  boilerplate/app/models/EpisodeStore.ts
  boilerplate/app/screens/DemoCommunityScreen.tsx
  boilerplate/app/screens/DemoComponentsScreen/DemoComponentsScreen.tsx
  boilerplate/app/screens/DemoDebugScreen.tsx
  boilerplate/app/screens/DemoPodcastListScreen.tsx
  boilerplate/app/theme/colors.ts
  boilerplate/assets/images/rnr-image-1@2x.png
  boilerplate/assets/images/rnr-image-1@3x.png
  boilerplate/assets/images/rnr-image-2.png
  boilerplate/assets/images/rnr-image-2@2x.png
  boilerplate/assets/images/rnr-image-2@3x.png
  boilerplate/assets/images/rnr-image-3.png
  boilerplate/assets/images/rnr-image-3@2x.png
  boilerplate/assets/images/rnr-image-3@3x.png
  boilerplate/assets/images/rnr-image.png
Labels: design, maverick

#2182 Formatted code snipper for Card docs
  docs/Components-Card.md
Labels: docs, maverick

#2177 [maverick] Adds Release docs
  docs/README.md
  docs/Releases.md
  docs/Tour-of-Ignite.md
  package.json
Labels: maverick

#2181 Updates Button docs; Renames DemoComponents screen to DemoShowroom
  boilerplate/app/components/Button.tsx
  boilerplate/app/navigators/DemoNavigator.tsx
  boilerplate/app/screens/DemoShowroomScreen/DemoDivider.tsx
  boilerplate/app/screens/DemoShowroomScreen/DemoShowroomScreen.tsx
  boilerplate/app/screens/DemoShowroomScreen/DemoUseCase.tsx
  boilerplate/app/screens/DemoShowroomScreen/DrawerIconButton.tsx
  boilerplate/app/screens/DemoShowroomScreen/demos/DemoAutoImage.tsx
  boilerplate/app/screens/DemoShowroomScreen/demos/DemoButton.tsx
  boilerplate/app/screens/DemoShowroomScreen/demos/DemoCard.tsx
  boilerplate/app/screens/DemoShowroomScreen/demos/DemoHeader.tsx
  boilerplate/app/screens/DemoShowroomScreen/demos/DemoIcon.tsx
  boilerplate/app/screens/DemoShowroomScreen/demos/DemoListItem.tsx
  boilerplate/app/screens/DemoShowroomScreen/demos/DemoText.tsx
  boilerplate/app/screens/DemoShowroomScreen/demos/DemoTextField.tsx
  boilerplate/app/screens/DemoShowroomScreen/demos/DemoToggle.tsx
  boilerplate/app/screens/DemoShowroomScreen/demos/index.ts
  boilerplate/app/screens/WelcomeScreen.tsx
  boilerplate/app/screens/index.ts
  docs/Components-Button.md
  docs/Components-TextField.md
  src/tools/demo.test.ts
  test/vanilla/__snapshots__/ignite-remove-demo.test.ts.snap
Labels: maverick

#2179 [Maverick] Fix screen template, Detox
  boilerplate/ignite/templates/screen/NAMEScreen.tsx.ejs
  boilerplate/ios/Podfile.lock
  boilerplate/package.json
Labels: maverick

#2185 Docs/folder structure
  docs/Folder-Structure.md
Labels: maverick

#2186 docs(fonts): explanation of adding a custom font
  docs/Theming-Fonts-And-Typography.md
Labels: maverick

#2184 Simplify `.gitignore` copy logic
  src/commands/new.ts
Labels: bug, critical, maverick, cli

#2187 More Toggle updates.
  boilerplate/app/components/Button.tsx
  boilerplate/app/components/Toggle.tsx
  boilerplate/app/i18n/ar.ts
  boilerplate/app/i18n/en.ts
  boilerplate/app/i18n/ko.ts
  boilerplate/app/screens/DemoShowroomScreen/demos/DemoToggle.tsx
  boilerplate/ios/Podfile.lock
Labels: maverick

#2193 Updated docs/README.md
  docs/README.md
  docs/Theming-Spacing.md
Labels: docs, maverick

#2190 Initialize git repository on Windows using separate cmds in `new` command
  .github/PULL_REQUEST_TEMPLATE.md
  src/commands/new.ts
Labels: bug, maverick, cli

#2189 Add `--active-arch-only` to `yarn android`
  boilerplate/package.json
Labels: maverick

#2199 feat(doctor): added git version
  src/commands/doctor.ts
Labels: enhancement, maverick

#2202 Fix missing "Only Show Favorites" label on Demo Podcast screen
  boilerplate/app/screens/DemoPodcastListScreen.tsx
Labels: bug, maverick

#2196 Fill out `docs/Testing.md`
  boilerplate/package.json
  docs/Testing.md
Labels: docs, maverick

#2194 Add Error Boundary docs
  boilerplate/app/screens/ErrorScreen/ErrorBoundary.tsx
  docs/Error-Boundary.md
Labels: docs, maverick

#2207 fix(boilerplate): add expo-file-system dependency (#2206)
  boilerplate/package.json
Labels: maverick

#2209 Remove jetify from post install
  boilerplate/bin/postInstall
  boilerplate/package.json
Labels: enhancement, maverick

#2212 refactor(boilerplate, docs): MAVERICKTODOS -> TODOS
  boilerplate/app/components/AutoImage.tsx
  boilerplate/app/components/EmptyState.tsx
  boilerplate/app/theme/colors.ts
  boilerplate/app/theme/typography.ts
  boilerplate/react-native.config.js
  docs/Expo-and-Ignite.md
  docs/Navigation.md
  docs/Styling.md
Labels: docs, maverick

#2213 Remove MAVERICKTODOS from generators
  boilerplate/ignite/templates/component/NAME.tsx.ejs
  boilerplate/ignite/templates/navigator/NAMENavigator.tsx.ejs
  boilerplate/ignite/templates/screen/NAMEScreen.tsx.ejs
Labels: maverick

#2221 chore(docs): Fixing Releasing Ignite link
  docs/Releasing-Ignite.md
Labels: docs

#2222 Added EmptyState documentation
  boilerplate/app/components/EmptyState.tsx
  docs/Components-EmptyState.md
  docs/Components.md
  docs/Folder-Structure.md
  docs/README.md
Labels: docs

#2235 fix(cache): remove ios/xcode.env.local copy
  src/tools/cache.ts
Labels: bug, cli
