Repository infinitered/ignite, pull requests merged in 2022-10, with the labels that each got.

#2229 docs(components): Add documentation for new Maverick Toggle Component
  docs/Components-Toggle.md
  docs/Components.md
Labels: docs

#2252 fix(package.json): pin "react-error-overlay": "6.0.9"
  boilerplate/package.json
Labels: bug

#2250 Fix demo screen and screen generator typings
  boilerplate/app/screens/DemoCommunityScreen.tsx
  boilerplate/app/screens/DemoDebugScreen.tsx
  boilerplate/app/screens/DemoPodcastListScreen.tsx
  boilerplate/app/screens/DemoShowroomScreen/DemoShowroomScreen.tsx
  boilerplate/app/screens/LoginScreen.tsx
  boilerplate/app/screens/WelcomeScreen.tsx
  boilerplate/ignite/templates/screen/NAMEScreen.tsx.ejs
  src/tools/generators.ts
Labels: bug, cli

#2254 fix(api): remove-curent-line to remove-current-line
  boilerplate/app/services/api/api.ts
Labels: bug
